<Project>
    <Sdk Name="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>directons.ico</ApplicationIcon>
    <Deterministic>false</Deterministic>
    <AssemblyVersion>1.0.*</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Configurations>Debug;Release;EasyTest</Configurations>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>xRoadMap.Win</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="DevExpress.ExpressApp.ListView" Alias="ListView" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Model.xafml" />
    <None Remove="Images\Logo.svg" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="directons.ico" />
    <Content Include="Model.xafml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Images\Logo.svg" />
    <EmbeddedResource Include="Images\ExpressAppLogo.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.ExpressApp" Version="26.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.CodeAnalysis" Version="26.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.FileAttachment.Win" Version="26.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.ReportsV2.Win" Version="26.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.Security.Xpo" Version="26.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.Validation.Win" Version="26.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.Win" Version="26.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.Win.Design" Version="26.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.Xpo" Version="26.1.*" />
    <PackageReference Include="DevExpress.Persistent.Base" Version="26.1.*" />
    <PackageReference Include="DevExpress.Persistent.BaseImpl.Xpo" Version="26.1.*" />
    <PackageReference Include="DevExpress.RichEdit.Export" Version="26.1.*" />
    <PackageReference Include="DevExpress.Win.Design" Version="26.1.*" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.7.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\xRoadMap.Module\xRoadMap.Module.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="it\DevExpress.AIIntegration.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.AIIntegration.WinForms.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.AspNetCore.RichEdit.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Blazor.PivotTable.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Blazor.Reporting.v26.1.Viewer.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Blazor.RichEdit.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Blazor.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Blazor.v26.1.Viewer.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Charts.Designer.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Dashboard.v26.1.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Dashboard.v26.1.Web.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Dashboard.v26.1.Win.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Data.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.DataAccess.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.DataAccess.v26.1.UI.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Diagram.v26.1.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Dialogs.v26.1.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Drawing.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.EntityFrameworkCore.Security.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.AI.Blazor.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.AI.Win.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.AuditTrail.Xpo.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.Blazor.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.Chart.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.CloneObject.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.Dashboards.Blazor.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.Dashboards.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.Dashboards.Win.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.FileAttachment.Blazor.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.FileAttachment.Win.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.Notifications.Blazor.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.Notifications.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.Office.Blazor.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.Office.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.Office.Win.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.PivotGrid.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.ReportsV2.Blazor.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.ReportsV2.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.ReportsV2.Win.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.Scheduler.Blazor.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.Scheduler.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.Scheduler.Win.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.Security.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.Security.Xpo.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.StateMachine.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.Validation.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.Validation.Win.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.ViewVariantsModule.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ExpressApp.Win.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Map.v26.1.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Mvvm.v26.1.DataModel.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Office.v26.1.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Pdf.v26.1.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Persistent.Base.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Persistent.BaseImpl.EFCore.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Persistent.BaseImpl.Xpo.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.PivotGrid.v26.1.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Printing.v26.1.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.ReportServer.v26.1.Localization.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.RichEdit.v26.1.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Snap.v26.1.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Snap.v26.1.Extensions.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Snap.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Sparkline.v26.1.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Spreadsheet.v26.1.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Utils.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Utils.v26.1.UI.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Web.ASPxDiagram.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Web.ASPxGantt.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Web.ASPxHtmlEditor.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Web.ASPxRichEdit.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Web.ASPxScheduler.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Web.ASPxSpellChecker.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Web.ASPxSpreadsheet.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Web.ASPxTreeList.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Web.Resources.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Web.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Xpf.Charts.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Xpf.CodeView.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Xpf.Controls.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Xpf.Core.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Xpf.Docking.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Xpf.DocumentViewer.v26.1.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Xpf.Gantt.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Xpf.Gauges.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Xpf.Grid.v26.1.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Xpf.LayoutControl.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Xpf.NavBar.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Xpf.PdfViewer.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Xpf.Printing.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Xpf.PropertyGrid.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Xpf.ReportDesigner.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Xpf.Ribbon.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Xpf.RichEdit.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Xpf.Scheduler.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Xpf.Scheduling.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Xpf.SpellChecker.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Xpf.Spreadsheet.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.Xpo.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraBars.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraCharts.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraCharts.v26.1.Wizard.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraEditors.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraGantt.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraGauges.v26.1.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraGauges.v26.1.Presets.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraGrid.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraLayout.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraNavBar.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraPdfViewer.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraPivotGrid.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraPrinting.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraReports.v26.1.Extensions.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraReports.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraReports.v26.1.Web.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraRichEdit.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraScheduler.v26.1.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraScheduler.v26.1.Extensions.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraScheduler.v26.1.Reporting.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraScheduler.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraSpellChecker.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraSpreadsheet.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraTreeList.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraVerticalGrid.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="it\DevExpress.XtraWizard.v26.1.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="UnusableNodes.xml">
      <DependentUpon>Model.xafml</DependentUpon>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="it\" />
  </ItemGroup>
</Project>
