<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <Deterministic>false</Deterministic>
    <AssemblyVersion>1.0.*</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Configurations>Debug;Release;EasyTest</Configurations>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>xRoadMap.Blazor.Server</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Model.xafml" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Model.xafml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.Drawing.Skia" Version="26.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.Blazor" Version="26.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.CodeAnalysis" Version="26.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.FileAttachment.Blazor" Version="26.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.ReportsV2.Blazor" Version="26.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.Security.Xpo" Version="26.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.Validation.Blazor" Version="26.1.*" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="8.0.17" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.7.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\xRoadMap.Module\xRoadMap.Module.csproj" />
  </ItemGroup>
</Project>
